# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IpWatch < Formula
  desc "Keep cloud-provider IP ranges applied to your webserver/firewall"
  homepage "https://github.com/rezmoss/ip-watch"
  version "0.0.3"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/rezmoss/ip-watch/releases/download/v0.0.3/ip-watch_0.0.3_linux_x86_64.tar.gz"
    sha256 "9e439d18371f5c1e0a7a1b32a3fe259f2f26adc8a293f43793714aad2abfe865"
    define_method(:install) do
      bin.install "ip-watch"
    end
  end
  if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/rezmoss/ip-watch/releases/download/v0.0.3/ip-watch_0.0.3_linux_armv6.tar.gz"
    sha256 "b80a86b8832bee2217bd956f512168d2d1b2c55922bef535948e38c9805440ec"
    define_method(:install) do
      bin.install "ip-watch"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rezmoss/ip-watch/releases/download/v0.0.3/ip-watch_0.0.3_linux_arm64.tar.gz"
    sha256 "ae75669c6b446585269a626ba97749a371905b639a2ef4d2d2ff30d4059db578"
    define_method(:install) do
      bin.install "ip-watch"
    end
  end

  def caveats
    <<~EOS
      ip-watch manages Linux webservers/firewalls via a systemd service and runs
      as root. This formula installs the binary only — for the managed service use
      the .deb/.rpm/.apk or: curl -fsSL https://raw.githubusercontent.com/rezmoss/ip-watch/main/install.sh | sudo sh
      Get started with: ip-watch help
    EOS
  end

  test do
    assert_match "ip-watch", shell_output("#{bin}/ip-watch version")
  end
end
