# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IpWatch < Formula
  desc "Keep cloud-provider IP ranges applied to your webserver/firewall"
  homepage "https://github.com/rezmoss/ip-watch"
  version "0.0.4"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/rezmoss/ip-watch/releases/download/v0.0.4/ip-watch_0.0.4_linux_x86_64.tar.gz"
    sha256 "70707fe02ea2ab34f9724a8c9cca1642a8ebae6f33e2505326bfdc35dc6ceb1b"
    define_method(:install) do
      bin.install "ip-watch"
    end
  end
  if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/rezmoss/ip-watch/releases/download/v0.0.4/ip-watch_0.0.4_linux_armv6.tar.gz"
    sha256 "f75aaba3b8c27fc1f6a78e59b76294c5aee007b51069169769e207516c731b71"
    define_method(:install) do
      bin.install "ip-watch"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rezmoss/ip-watch/releases/download/v0.0.4/ip-watch_0.0.4_linux_arm64.tar.gz"
    sha256 "fc1bbb8277555ecc91b2aa9d3f185aba8b55c682f23008884c039334b0802c12"
    define_method(:install) do
      bin.install "ip-watch"
    end
  end

  def caveats
    <<~EOS
      ip-watch manages Linux webservers/firewalls via a systemd service and runs
      as root. This formula installs the binary only — for the managed service use
      the .deb/.rpm/.apk or: curl -fsSL https://raw.githubusercontent.com/rezmoss/ip-watch/main/install.sh | sudo sh
      Get started with: ip-watch help
    EOS
  end

  test do
    assert_match "ip-watch", shell_output("#{bin}/ip-watch version")
  end
end
