# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IpWatch < Formula
  desc "Keep cloud-provider IP ranges applied to your webserver/firewall"
  homepage "https://github.com/rezmoss/ip-watch"
  version "0.0.5"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/rezmoss/ip-watch/releases/download/v0.0.5/ip-watch_0.0.5_linux_x86_64.tar.gz"
    sha256 "1beb3d2ac57014e08b7a85f08ae7b4ee448e2c19b41141bd377b21ff3802906c"
    define_method(:install) do
      bin.install "ip-watch"
    end
  end
  if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/rezmoss/ip-watch/releases/download/v0.0.5/ip-watch_0.0.5_linux_armv6.tar.gz"
    sha256 "4b8e157d0940d4b61b301a9a7fcc547c07ac1c4b7f750bd14e262bb32c7dfd6e"
    define_method(:install) do
      bin.install "ip-watch"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rezmoss/ip-watch/releases/download/v0.0.5/ip-watch_0.0.5_linux_arm64.tar.gz"
    sha256 "dc6a4287ee78fae780bba8e94c1503f976dbcc05b6e64337265125aa02b68b9b"
    define_method(:install) do
      bin.install "ip-watch"
    end
  end

  def caveats
    <<~EOS
      ip-watch manages Linux webservers/firewalls via a systemd service and runs
      as root. This formula installs the binary only — for the managed service use
      the .deb/.rpm/.apk or: curl -fsSL https://raw.githubusercontent.com/rezmoss/ip-watch/main/install.sh | sudo sh
      Get started with: ip-watch help
    EOS
  end

  test do
    assert_match "ip-watch", shell_output("#{bin}/ip-watch version")
  end
end
